[workspace]
members = ["crates/git-smee-cli", "crates/git-smee-core"]

resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Eran Riesenfeld"]
license = "MIT"
repository = "https://github.com/errfld/git-smee"
