[package]
name = "git-smee-core"
version.workspace = true
edition.workspace = true

[dependencies]
toml = { version = "0.9" }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2" }
rayon = { version = "1" }

[dev-dependencies]
tempfile = "3"
assert2 = { workspace = true }
