[package]
name = "git-smee-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "git-smee"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
git-smee-core = { path = "../git-smee-core" }
